name: Build sdcafiine
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project (Makefile)
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sdcafiine_plus
          path: |
            *.wps
            *.wuhb
            *.elf