name: Build WiiU Plugin

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # БЕРЕМ ОБРАЗ СПЕЦИАЛЬНО ДЛЯ WII U (многое уже установлено)
      image: devkitpro/wiiudev:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix DevkitPro Network & Install deps
        run: |
          # Выключаем таймауты, чтобы он не сбрасывал соединение при медленной скорости
          echo "DisableDownloadTimeout" >> /opt/devkitpro/pacman/etc/pacman.conf
          # Качаем только 3 пакета без полного обновления системы (-Sy вместо -Syu)
          dkp-pacman -Sy --noconfirm wiiu-wut wiiu-wups wiiu-wums

      - name: Build project (Make)
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdcafiine_build_files
          path: |
            **/*.wps
            **/*.elf
            **/*.wuhb
