name: Build WiiU Plugin

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # ВОТ ЭТОТ НОВЫЙ ШАГ: скачиваем нужные библиотеки WUPS, WUT и WUMS
      - name: Install Wii U dependencies
        run: |
          dkp-pacman -Syu --noconfirm wiiu-wut wiiu-wups wiiu-wums

      - name: Build project (Make)
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdcafiine_build_files
          path: |
            **/*.wps
            **/*.elf
            **/*.wuhb
